### ISSUE TITLE
Parameters b, srcband or dstband  no working. Version1.1.0

### ISSUE THREAD

**Issue by gonzalezivan90** [JoshOBrien/gdalUtilities#14]
Hello. I have a multlayer raster and only need first one, or other index, but only one layer.
I tried with several parameters the following function and doesn't work.

gdalUtilities::gdalwarp(srcfile = inraster,  dstfile = outraster, 
                        ot = 'Float64', 
                        #dstband = 1, #not working
                        # b = 1,  #not working
                        # srcband = 1, #not working
                        tr = rep(max(pixsize), 2), 
                        srcnodata = nd,
                        dstnodata = -9999)

Thanks

**Comment by JoshOBrien** [comment]
Would you please prepare a minimal reproducible example ([see here](https://stackoverflow.com/help/minimal-reproducible-example) if you are not familiar with that term), with the code you used, and a small sample multilayer raster on which that code fails? Without that, there's not much I can do to learn where the problem lies.

Thanks!
